class_name Global_Constants
const PHYS_FRAMES_TO_ANIM_FRAMES = 6
const PHYS_FRAME_DELTA = 0.01666666667
#const TILE_WIDTH_PIXELS = 32
#const TILE_HEIGHT_PIXELS = 32
const MAP_WIDTH_TILES =  36
const MAP_HEIGHT_TILES = 20
